env:
  node: true
  es2021: true
  googleappsscript/googleappsscript: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
globals:
  GoogleAppsScript: readonly
  People: readonly
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - googleappsscript
rules:
  '@typescript-eslint/no-unused-vars': error
  no-console: [error, { allow: [info, warn, error] }]
  no-unused-vars: 'off'
  no-underscore-dangle: 'off'
  import/prefer-default-export: 'off'
  import/extensions: [error, ignorePackages, { ts: never, js: never }]
